language: ruby
rvm:
  - 2.0.0
before_install:
  - "apt-get update"
  - "apt-get install vim-gnome"
  - "vim --version"
install: bundle
script: xvfb-run bundle exec rspec --format documentation
sudo: false
notifications:
  email: false
